// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmnrdgnhahkwfdwqlqau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtbnJkZ25oYWhrd2Zkd3FscWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDg2NTMsImV4cCI6MjA2Nzk4NDY1M30.OaEDpAbTLeIKKBCkIXNSS-cHPOR79PWOU1xFmeiNW8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});